# Generated by Django 3.0.7 on 2020-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(default='default.pdf', upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='report',
            name='upload_report',
            field=models.FileField(upload_to='reports'),
        ),
    ]
