# Generated by Django 3.0.7 on 2020-07-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_auto_20200702_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(default='default.pdf', upload_to='certificates/pdf'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_png',
            field=models.FileField(default='default.png', upload_to='certificates/png'),
        ),
    ]
